### ISSUE TITLE
[Bug]: E-Commerce Framework cannot be installed without DE langauge configured

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#10359]
### Expected behavior

To be able to install E-Commerce Framework without enabling the German language

### Actual behavior

https://github.com/pimcore/pimcore/blob/4550a053fac47a1d2c0406bf15c9799ef078bbb7/bundles/EcommerceFrameworkBundle/Tools/Installer.php#L178

Throws an error: `Warning: Undefined array key "de"`

### Steps to reproduce

In System Settings the following languages are enabled:

- English (en)
- Danish (da)
- Norwegian Bokmål (nb)
- Swedish (sv)

**Comment by dvesh3** [comment]
@NiklasBr how it is related to languages selected in System settings since `EcommerceFrameworkBundle\Tools\Installer::installTranslations()` is responsible for importing admin translations (https://github.com/pimcore/pimcore/blob/10.x/bundles/EcommerceFrameworkBundle/Tools/Installer.php#L382) and German is always there from CoreBundle.

**Comment by NiklasBr** [comment]
That was just a guess, I could not figure out why it crashed on that language and the system language was a likely candidate.

**Comment by NiklasBr** [comment]
@dvesh3 Whatever the reason, it prevents us from installing the framework bundle:
![image](https://user-images.githubusercontent.com/279826/134464983-807e096f-75d0-4e32-aa95-9142649efe4f.png)

**Comment by dvesh3** [comment]
@NiklasBr could you please share stack trace? thanks!

**Comment by NiklasBr** [comment]
Details in the admin UI:
```log
Timestamp: Thu Sep 23 2021 10:37:07 GMT+0200 (Central European Summer Time)
Status: 400 | Bad Request
URL: /admin/extensionmanager/admin/install
Method: POST
Message: Warning: Undefined array key "de"
```

**Comment by NiklasBr** [comment]
Odd thing here is that the file [admin-translations/init.csv](https://github.com/pimcore/pimcore/blob/10.x/bundles/EcommerceFrameworkBundle/Resources/install/admin-translations/init.csv)  might be malformed

**Comment by NiklasBr** [comment]
Changing [line break](https://datatracker.ietf.org/doc/html/rfc4180) from `LF` to `CRLF` seems to work. Maybe `importTranslationsFromFile()` should replace any non-escaped `LF` with `CRLF`?

**Comment by dvesh3** [comment]
@NiklasBr yes, I would do fix it in `importTranslationsFromFile()`. please provide a PR with suggested fix. thanks!

**Comment by NiklasBr** [comment]
@dvesh3 I am unable to, which is why I created this issue.

**Comment by dvesh3** [comment]
Fixed by #10407

**Comment by NiklasBr** [comment]
@dvesh3 the patch did not work to resolve the installation error, it seems the [CSV still does not validate](https://github.com/pimcore/pimcore/blob/c7c6da7818ba4234533a58ea4d22ec103281dd6c/bundles/EcommerceFrameworkBundle/Resources/install/admin-translations/init.csv):

 > We can make this file beautiful and searchable if this error is corrected: Any value after quoted field isn't allowed in line 1.

**Comment by dvesh3** [comment]
@NiklasBr could you please check if this PR https://github.com/pimcore/pimcore/pull/10416 fixes the issue? thanks!

**Comment by NiklasBr** [comment]
Same problem in the local environment:
![image](https://user-images.githubusercontent.com/279826/134886098-5f0029dc-67cb-475a-a462-7e0cf4238218.png)


And GitHub still complains about the file: 
> It looks like row 55 should actually have 1 column, instead of 3. in line 54.

**Comment by NiklasBr** [comment]
Further stepping through the errors this is closer to where it breaks:

![image](https://user-images.githubusercontent.com/279826/134898684-929810f6-3908-4aaa-a8e5-6e34328e52a7.png)

And on the next step we see where the error happens:
![image](https://user-images.githubusercontent.com/279826/134898775-5d0338c5-af47-4f10-8f95-8f64460856d1.png)

**Comment by NiklasBr** [comment]
Some other translations appear to have all languages in comparison:
![image](https://user-images.githubusercontent.com/279826/134900160-3bb8f957-9b42-4102-9959-33d2e0afc322.png)

**Comment by dvesh3** [comment]
> Further stepping through the errors this is closer to where it breaks:
> 
> ![image](https://user-images.githubusercontent.com/279826/134898684-929810f6-3908-4aaa-a8e5-6e34328e52a7.png)
> 
> And on the next step we see where the error happens:
> ![image](https://user-images.githubusercontent.com/279826/134898775-5d0338c5-af47-4f10-8f95-8f64460856d1.png)

@NiklasBr I believe calling `$t->hasTranslation($key)` before getTranslation should fix the issue. could you please give it a try? 
like:
```
$currentTranslation = $t->hasTranslation($key) ? $t->getTranslation($key) : null;
```
and change else part to just use `$currentTranslation` var.

**Comment by NiklasBr** [comment]
@dvesh3 I think that worked 👍

**Comment by dvesh3** [comment]
please review https://github.com/pimcore/pimcore/pull/10416

**Comment by NiklasBr** [comment]
✔️ have verified that installation now works, translations gets added and no errors happens.

**Comment by dvesh3** [comment]
> ✔️ have verified that installation now works, translations gets added and no errors happens.

Thanks @NiklasBr

**Comment by dvesh3** [comment]
Fixed by #10416
