### ISSUE TITLE
[Bug]: Sorter for groups in classificationstore is still not considered

### ISSUE THREAD

**Issue by dpfahlbusch** [pimcore/pimcore#10517]
### Expected behavior

Groups are sorted via sorter

### Actual behavior

Groups are sorted via internal id

### Steps to reproduce

1. Go to demo.pimcore.fun
2. Create ClassificationStore, add groups and keys with sorters
3. Add Group to an object
4. Groups is sorted via sorter
5. Save and reload object
6. Groups are sorted via internal id

**Comment by dpfahlbusch** [comment]
There was an previous issue #10273 , maybe @dturopoli you have an idea?

**Comment by dturopoli** [comment]
@dpfahlbusch I think that there was a misunderstanding, my fix only fixed sorting of keys inside a group.

**Comment by dpfahlbusch** [comment]
Seems like the problem is that `this.activeGroups` in `bundles/AdminBundle/Resources/public/js/pimcore/object/tags/classificationstore.js` is an object instead of an array, so it always sorts the keys.
Maybe someone has a good idea :)

**Comment by NiklasBr** [comment]
Wasn't this resolved by #10296?

**Comment by brusch** [comment]
@NiklasBr yep, thanks for the hint!

**Comment by gresa-neziri** [comment]
Sorter for groups in classificationstore still doesn't work on the edit mode of dataobject!
The groups inside a classification store field are sorted via internal id of the groups!
