### ISSUE TITLE
[Bug]: Domain input for URL Slug is hidden since Pimcore X

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#10604]
### Expected behavior

All fields should be visible in the Ext JS interface.

### Actual behavior

The domain-specific URL Slug field (and its button is hidden:
![image](https://user-images.githubusercontent.com/279826/137320821-9510356f-2ef9-440f-86e2-f6d96fe98fe7.png)
![image](https://user-images.githubusercontent.com/279826/137321189-7be993c0-9f4c-4742-bd7c-8910f83b6239.png)

By manually adjusting the height of the elements in the DOM it is possible to show that both fields are available, just hidden behind some inline `height` attributes:
![image](https://user-images.githubusercontent.com/279826/137322148-efe92b8e-c509-4f7e-9464-b0eff633a364.png)

### Steps to reproduce

Putting a URL Slug in a fieldset which in turn is in a Localized fields 

![image](https://user-images.githubusercontent.com/279826/137320674-9fb7d384-da9a-42fb-8166-ca95f6b2d39f.png)

**Comment by NiklasBr** [comment]
@dvesh3 this can be reproduced on the demo site as well by adding additional sites with domains:

![image](https://user-images.githubusercontent.com/279826/137714915-afe62321-3ead-4245-a407-0b4281fa57da.png)

**Comment by dvesh3** [comment]
Fixed by #10638

**Comment by passioneight** [comment]
Seems like this bug is back as of v10.3.0 -  for localized fields. Reproducible on Pimcore Demo:

<img width="581" alt="image" src="https://user-images.githubusercontent.com/57256630/154045648-4560170c-c5fc-4076-af81-09135e74129f.png">

**Comment by dvesh3** [comment]
Could you please try to reproduce on [demo.pimcore.fun](https://demo.pimcore.fun/)?

**Comment by passioneight** [comment]
@dvesh3 the screenshot is from the pimcore demo.

**Comment by dvesh3** [comment]
I was not able to reproduce it on pimcore.fun

**Comment by NiklasBr** [comment]
I can get it to disappear if there is one slug outside the localized fields and one inside

![image](https://user-images.githubusercontent.com/279826/154116200-996ac5f6-1144-4213-b01f-0759318773dc.png)

![image](https://user-images.githubusercontent.com/279826/154116263-3366e31a-82c3-4b1c-8ae9-653834c72b00.png)

**Comment by dvesh3** [comment]
Still works for me (Also tried with clearing cache):
![image](https://user-images.githubusercontent.com/5137917/154226488-fb7dfa70-2093-40cb-b55e-f7b98f7db8c8.png)

**Comment by NiklasBr** [comment]
@dvesh3 see [my comment again](https://github.com/pimcore/pimcore/issues/10604#issuecomment-945632132), the **site** selector drop-down is missing in these screen shots.

**Comment by passioneight** [comment]
It does not seem to be related to multiple slugs in one object though. Here's the relevant part of our class definition:

<img width="251" alt="image" src="https://user-images.githubusercontent.com/57256630/154261133-7e20b0b5-598d-466a-93b6-a37b288f0d71.png">

The "SEO"-Panel is within a `Tabpanel` and that's about all there is to it. Here's how it looks when opening an object of this type:

<img width="1500" alt="image" src="https://user-images.githubusercontent.com/57256630/154261335-633ae2e3-e83d-4489-a985-a8ff5f347bfa.png">

The `Not editable` flag is set, but it doesn't matter as I just verified by changing the class definition and reloading the object.

Additionally, @NiklasBr comment states that the fields are hidden. In this case, they are not even in the DOM.

----

Update:
I also tried the Pimcore Demo once more - still not working:

<img width="1261" alt="image" src="https://user-images.githubusercontent.com/57256630/154262384-6e0db367-af59-423b-8be4-674f32e11cc8.png">

**Comment by dvesh3** [comment]
@passioneight I see your changes on demo.pimcore.com and it works for me. could you please check for console errors?
![image](https://user-images.githubusercontent.com/5137917/154453316-9acd7502-4d93-4598-837d-2fc9b3132f94.png)

**Comment by NiklasBr** [comment]
No site for me, no relevant console errors or warnings
![image](https://user-images.githubusercontent.com/279826/154457577-9a255e57-a482-4f90-8e37-c5362efe3195.png)

**Comment by dvesh3** [comment]
yes, because you utilized all the sites available so you don't see the dropdown anymore. when you remove testsite.local then you'll see it.

**Comment by NiklasBr** [comment]
Sites are still missing: 
![image](https://user-images.githubusercontent.com/279826/154464172-a56f6cdc-1c9f-4a7f-b3fe-eba6426e3d8d.png)

Neither the site called *blank* nor the site called *PimcoreHome* are available.

**Comment by passioneight** [comment]
@dvesh3 no errors in the console. However, I now see the site dropdown and can add the sites listed as options. Though, I couldn't verify if other sites are working or not, as I couldn't create a new site. Maybe @NiklasBr can try once more?

**Comment by NiklasBr** [comment]
This is the easiest way to reproduce my issue at the moment I can think of.

1. No localized field and not limited to any specific Site in class definition. The Site drop-down works here:
![image](https://user-images.githubusercontent.com/279826/154491601-fabed998-276a-4d5b-be86-6c3bc2f5c5ac.png)
![image](https://user-images.githubusercontent.com/279826/154491554-5aa37f89-2825-4f57-bc80-16ddcb072dbd.png)

2. With slug moved into localized field and no limits on Sites in class definition, the Site drop-down disappears:
![image](https://user-images.githubusercontent.com/279826/154491699-6996c5fc-f421-465d-b5aa-fd4d0357c5bf.png)
![image](https://user-images.githubusercontent.com/279826/154491753-1516a3e7-e439-449e-8f4c-69428ec7fb0d.png)

**Comment by dvesh3** [comment]
you have to select the sites in dropdown then only they appear in the list:
![image](https://user-images.githubusercontent.com/5137917/154651006-bf1992ec-a4db-4c04-8c18-0dc22a8405df.png)

There was a bug that selection no displayed in admin, which is now fixed with https://github.com/pimcore/pimcore/pull/11487

**Comment by NiklasBr** [comment]
This is very inconsistent now, in other places such as asset relations no selection = all selections, so _of course_ it should be the same here, for example no selection in Relation fields allows us to do this:

![image](https://user-images.githubusercontent.com/279826/154653053-eed4c60c-dba8-4414-883b-ee90b9f3a24f.png)

Why is this different and why is it not clearly documented and why is it not preventing the class from being saved if it is a hard requirement for the field to work properly?

**Comment by passioneight** [comment]
I agree with @NiklasBr. The sites in our project were never selected before, yet all of them were displayed until recently. That would also be the behaviour I'd expect due to the reason @NiklasBr stated.

**Comment by NiklasBr** [comment]
@dvesh3 what is the timeline here? This issue got worse since https://github.com/pimcore/pimcore/pull/11487

**Comment by dvesh3** [comment]
This is not priority for us at the moment. A PR would be nice to fix the issue 😉

**Comment by NiklasBr** [comment]
I would _gladly and promptly_ provide a PR if there was documentation how this was supposed to work.

**Comment by dvesh3** [comment]
> This is very inconsistent now, in other places such as asset relations no selection = all selections, so _of course_ it should be the same here, for example no selection in Relation fields allows us to do this:
> 
> ![image](https://user-images.githubusercontent.com/279826/154653053-eed4c60c-dba8-4414-883b-ee90b9f3a24f.png)
> 
> Why is this different and why is it not clearly documented and why is it not preventing the class from being saved if it is a hard requirement for the field to work properly?

Like you said before, I would keep it consistent with other places in admin.

**Comment by NiklasBr** [comment]
> Like you said before, I would keep it consistent with other places in admin.

Then it appears we are in agreement, why did you [explicitly make it inconsistent](https://github.com/pimcore/pimcore/issues/10604#issuecomment-1044176324)?

**Comment by dvesh3** [comment]
@NiklasBr please test #11698

**Comment by NiklasBr** [comment]
@dvesh3 that partially fixed the issue, the site-specific field appeared, but the fallback remains empty

**Comment by dvesh3** [comment]
@NiklasBr please check your response data. In my case, the fallback value is there (`with site Id = 0`):
![image](https://user-images.githubusercontent.com/5137917/159234469-5f0c7d92-11f4-4ddb-89c1-21cdb67fb309.png)

**Comment by NiklasBr** [comment]
@dvesh3 Not working, not in demo site either:

![image](https://user-images.githubusercontent.com/279826/159238635-4fd0225a-b722-4ef3-a4ee-b9d80c5635aa.png)

![image](https://user-images.githubusercontent.com/279826/159238763-f4955f55-8dc2-4d82-b4ad-c252c2308f03.png)

**Comment by kingjia90** [comment]
@NiklasBr the demo didn't have the changes of #11698 at that time, i've just reviewed and merged it.

The problem of fallback slug remaining empty happens when you set the slug set for siteIds that are not consecutive, eg. 0,3,4,5 which JS(?) guesses it is as an Object instead of Array (because indexes 1,2 are missing), see:

![image](https://user-images.githubusercontent.com/6014195/159733458-0f503f5c-c196-4263-8722-b92399d6ac15.png)

All the functions in `bundles/AdminBundle/Resources/public/js/pimcore/object/tags/urlSlug.js` work on array and if they read an object, it will silently break (this.data.length would be `undefined`), so even the fallback url is not getting rendered.

By adding `array_values` in `models/DataObject/ClassDefinition/Data/UrlSlug.php` avoids the siteId from being used as the array index.

Could you please double check locally with the changes of #11698?

**Comment by NiklasBr** [comment]
@kingjia90 my comment https://github.com/pimcore/pimcore/issues/10604#issuecomment-1070946492 was specifically about https://github.com/pimcore/pimcore/pull/11698, I have tested it locally and the problem persisted.

**Comment by kingjia90** [comment]
@NiklasBr Ok, in this case, there might be something related, because the #11698 fixed the reproducible problems to me, at least i was able to reproduce the missing dropdown, no selection = select all by default and empty slugs. 

The `Unique constraint violated. Slug alreay used by object urlSlug, fieldname: urlSlug` (https://github.com/pimcore/pimcore/issues/10604#issuecomment-1073701197) happens when the same slug is used more than once in localized field (eg. `/test1` in `english` and in `german` too) and seems intended(?), but at least it's not changed by #11698.

In case the slugs are still empty, could you please share the `console.log(this.data)` on https://github.com/pimcore/pimcore/blob/211b1041907d5c2acfe5169b3bcbfe6e9ace4adb/bundles/AdminBundle/Resources/public/js/pimcore/object/tags/urlSlug.js#L27 for each Localizefield tab?

**Comment by NiklasBr** [comment]
> and seems intended(?)

Where is this documented? Also why do you believe it to be intended?

**Comment by brusch** [comment]
@NiklasBr in the code, we do not create docs for every single line of code 😉 (see also other frameworks ...).

**Comment by NiklasBr** [comment]
Really, @brusch?

You understand very well what I am asking for when I ask why something that *behaves like a bug and looks like a bug and feels like a bug* is claimed to be *working as intended*, you understand very well that I am _not_ asking for every line to be documented. You understand that I am asking for a design decision to be clarified to those who did not participate in its design and where that decision can be understood.

In fact this very conversation is proof that "in the code" is [not sufficient to convey how things should work](https://hackaday.com/2019/03/05/good-code-documents-itself-and-other-hilarious-jokes-you-shouldnt-tell-yourself/). A simple `// Fallbacks must be unique across sites and cannot be the same because X` had improved everyone's situation here very much.

And *strongly* disagree that other frameworks are just as lacking in documentation, see for example:
https://github.com/drupal/drupal/blob/9.4.x/core/lib/Drupal.php
https://github.com/drupal/drupal/blob/9.4.x/core/lib/Drupal/Component/DependencyInjection/Container.php
https://github.com/drupal/drupal/blob/9.4.x/core/lib/Drupal/Component/Transliteration/PhpTransliteration.php
https://github.com/drupal/drupal/blob/9.4.x/core/lib/Drupal/Core/Asset/AssetResolverInterface.php

https://github.com/laravel/framework/blob/9.x/src/Illuminate/Collections/Collection.php
https://github.com/laravel/framework/blob/9.x/src/Illuminate/Collections/Traits/EnumeratesValues.php
https://github.com/laravel/framework/blob/9.x/src/Illuminate/Http/Client/Response.php

https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/author-template.php
https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/canonical.php
https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/class-wp-customize-setting.php

https://github.com/yiisoft/yii2/blob/master/framework/base/Action.php
https://github.com/yiisoft/yii2/blob/master/framework/base/Controller.php
https://github.com/yiisoft/yii2/blob/master/framework/base/Widget.php

**Comment by brusch** [comment]
Well, I'm sorry if we can't fulfill your expectations, but it doesn't help if you ask for docs again and again😉
Others seem to be ok with working and improving Pimcore, and if there are any questions we are also always here to help or clarify things.

**Comment by kingjia90** [comment]
For "paperwork" purposes, i am closing this issue, since the initial problem described here and even on #11693 (JSON urlSlug was returned as object instead of array) are both objectively reproduced, confirmed and successfully fixed by the changes on #11698. 

I hope you agree with me to move this `Unique constraint violated. Slug alreay used by object urlSlug, fieldname: urlSlug` problem to #11697 (which seems more closely related) or in a new issue, invite providing a separate PR with a better Exception message and, if necessary, move the documentation discussion in the `Discussion` area; otherwise it makes difficult to keep the issue short, relevant and "reconstructable".
