### ISSUE TITLE
[Bug]: Asset video open link

### ISSUE THREAD

**Issue by vignesh-happiestminds** [pimcore/pimcore#12832]
### Expected behavior

Created new video attribute for class. On creating data object for the video attributes,

When i click on the video edit icon, Video panel pop up should come.
   

### Actual behavior

On the video attributes, When i click on the video edit icon, The Video editor panel not opened.
"Uncaught TypeError: Cannot read properties of undefined (reading 'includes')  at pimcore.helpers.editmode.openVideoEditPanel"

'if (allowedTypes.includes("asset")) {
        fieldPath.on("render", initDD);
        poster.on("render", initDD);
    }"

### Steps to reproduce

1.Created new video attribute for class. 
2.Create a new data object.,
3. click on the video edit icon on the video attribute

**Comment by vignesh-happiestminds** [comment]
@kingjia90  Any update on this issues.

**Comment by kingjia90** [comment]
@vignesh-happiestminds PR https://github.com/pimcore/pimcore/pull/12846 is under review will be likely released tomorrow (10.5.3). In the meantime, you can also have a try with the changes in the PR, to confirm it is fixing the problem.

**Comment by kingjia90** [comment]
Fixed by #12846

**Comment by vignesh-happiestminds** [comment]
@kingjia90 still this issues is not resolved on latest version pimcore 10.5.3. Also in the latest version new issue is created. We are unable to create a new Video attribute.

The video preview also is not working, showing below message  

"**The preview for this video is currently in progress. Please wait**"

**Comment by vignesh-happiestminds** [comment]
@dvesh3 When can i expect the pimcore 10.5.4 release.

**Comment by dvesh3** [comment]
@vignesh-happiestminds you can check planned dates here https://github.com/pimcore/pimcore/milestones

**Comment by dvesh3** [comment]
@vignesh-happiestminds please confirm if #12947 fixes the video open issue and for video preview issue, please refer to discussions https://github.com/pimcore/pimcore/discussions?discussions_q=video+preview

**Comment by vignesh-happiestminds** [comment]
@dvesh3 Thanks for the response . Now the it's not throwing any error on page.But still the video preview  is not working.

Whenever we upload the video into assets and open the video , on the console generating URL - 404
**http://abc.com/admin/asset/get-video-thumbnail?id=1208&width=265&aspectratio=true&_dc=1661316947221** 

When i opened the URL below issues has came.

Error  : "**Unable to get video thumbnail for video 1207**"

**Comment by dvesh3** [comment]
> Whenever we upload the video into assets and open the video , on the console generating URL - 404

@vignesh-happiestminds It works for me when uploading video in assets. please make sure you run `messenger:consume` command properly.

**Comment by vignesh-happiestminds** [comment]
@dvesh3  i have executed the command and still same issues. Please find the below steps to reproduce this issue. Also all the image extensions are enabled.

bin/console messenger:consume then i selected options "**pimcore_image_optimize**" , Then i cleared a cache and re-uploaded Video
second  time - 
bin/console messenger:consume then i selected options "**pimcore_core**" , Then i cleared a cache and re-uploaded Video

Still same issue.  My Pimcore version 10.5.13.

**Comment by dvesh3** [comment]
Please refer to discussions for further support on video previews, as this issue is about video data type in DataObjects. thanks!

**Comment by dvesh3** [comment]
Fixed by #12947

**Comment by plixus** [comment]
Hi, I have just updated to 10.5.4 but the problem persists. 
Clicking the Icon not opening Popup but throwing den reported Error.
_"Uncaught TypeError: Cannot read properties of undefined (reading 'includes') at pimcore.helpers.editmode.openVideoEditPanel"_

The only difference is that the video attribute is in a field collection.

**Comment by dvesh3** [comment]
@plixus yes, it is not completely fixed on 10.5.4. please see follow up PR https://github.com/pimcore/pimcore/pull/13035
