### ISSUE TITLE
[Bug]: [error] Migration Pimcore\Bundle\CoreBundle\Migrations\Version20201008101817 failed during Execution. Error: "An exception occurred while executing 'DROP VIEW IF EXISTS documents_editables;'

### ISSUE THREAD

**Issue by kanevbg** [pimcore/pimcore#13372]
### Expected behavior

Update without issues

### Actual behavior

Update fails with SQL error:
```
An error occurred when executing the "/opt/php/8.1.6/bin/php --php-ini=/opt/php/8.1.6/lib/php.ini bin/console --ansi doctrine:migrations:migrate -n --prefix Pimcore\Bundle\CoreBundle" command:

  Exit code: 1

  [notice] Migrating up to Pimcore\Bundle\CoreBundle\Migrations\Version22020614115124


  [error] Migration Pimcore\Bundle\CoreBundle\Migrations\Version20201008101817 failed during Execution. Error: "An exception occurred while executing 'DROP VIEW IF EXISTS documents_editables;':

  SQLSTATE[HY000]: General error: 1347 'pimcore_db.documents_editables' is not VIEW"

  In AbstractMySQLDriver.php line 128:

    An exception occurred while executing 'DROP VIEW IF EXISTS documents_editables;':

    SQLSTATE[HY000]: General error: 1347 'pimcore_db.documents_editables' is not VIEW


  In Exception.php line 18:

    SQLSTATE[HY000]: General error: 1347 'pimcore_db.documents_editables' is not VIEW


  In PDOConnection.php line 141:

    SQLSTATE[HY000]: General error: 1347 'pimcore_db.documents_editables' is not VIEW
```

### Steps to reproduce

Install Pimcore 10.5.7 and setup crontab as documented.
Run `COMPOSER_MEMORY_LIMIT=-1 composer update` to update (currently to 10.5.8).

**Comment by aashan10** [comment]
@kanevbg could not reproduce this issue on a fresh pimcore installation. I installed pimcore 10.5.7 using pimcore/demo and then updated pimcore/pimcore version 10 10.5.8. The upgrade completed without any errors.

**Comment by kanevbg** [comment]
@aashan10 It may be that you used the demo and the `MySQL view` was actually existing. I have done it with the skeleton, please check with that. You can check that if for any reason the view does not exists this exception will be thrown simple because that's how Percona MySQL responds to the command:
```
pimcore_db> DROP VIEW IF EXISTS non_existing_view_name;
[2022-10-20 10:46:54] [HY000][1347] 'pimcore_db.non_existing_view_name' is not VIEW
```
Do you agree that it's more stable to catch exceptions from execution of such statements from the migration procedures (specifically for all DROP VIEW IF EXISTS statements) in order to prevent failure in edge or less common cases?
![image](https://user-images.githubusercontent.com/11477130/196929403-4487fec1-a3c9-48a0-a455-51b0d5aafec9.png)
eg, to become something like:
```
try {
    $this->addSql('DROP VIEW IF EXISTS documents_editables;');
} catch (\Exception $e) {
}
```

**Comment by aashan10** [comment]
@kanevbg thanks for more info regarding this. I will test this with Percona and skeleton instances. 

The try-catch statements however I'm not so sure of. If something goes wrong during installation you'd expect pimcore to show the error instead of silently supressing the errors and you finding out later that there was an issue during the installation itself and because of which you are finding a regression bug which will be very difficult to debug. What do you say?

**Comment by kanevbg** [comment]
This is specific to each concrete migration case, however when you do `drop view IF EXISTS` it means you are okay to continue if it was not existing. So if you prefer you can check the exception message and detect if it reports `[HY000][1347]` and only then ignore the exception.

**Comment by dvesh3** [comment]
Fixed by #13438

**Comment by kanevbg** [comment]
@dvesh3 
Hey, I have to let you know that this change did not fixed the problem and that is because
`$this->addSql('DROP VIEW IF EXISTS documents_editables;');`
is not executing the SQL but only queues it for latter execution, which happens in method
`\Doctrine\Migrations\Version\DbalExecutor::executeMigration`
Can you think of other solution as I am not experienced with the symfony framework as much as pimcore team?

**Comment by brusch** [comment]
@kanevbg Thanks for the feedback, I can confirm this.

**Comment by dvesh3** [comment]
@kanevbg thanks for reporting. Could you please confirm if https://github.com/pimcore/pimcore/pull/13526 fixes the issue?

**Comment by kanevbg** [comment]
I will provide feedback tomorrow

**Comment by dvesh3** [comment]
Fixed by #13526
