### ISSUE TITLE
ElementInterface implementations should allow only int for $id param in getById() method

### ISSUE THREAD

**Issue by dvesh3** [pimcore/pimcore#14036]
### Improvement description

please see https://github.com/pimcore/pimcore/pull/13985

**Comment by dvesh3** [comment]
already fixed in #13474

**Comment by blankse** [comment]
@dvesh3 No it is not fixed. It is still int and string:
https://github.com/pimcore/pimcore/blob/b419ee7b7f7a95d0034590fbf0d957913846a07b/models/DataObject/AbstractObject.php#L213
