### ISSUE TITLE
[Bug]: Static Page Generator should not embed ESI content

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#14468]
### Expected behavior

Dynamically including ESI content should be possible with statically rendered pages using [Symfony Edge Side Includes](https://symfony.com/doc/5.4/http_cache/esi.html).

We expect the generated HTML to respect ESI tags which are used by a gateway. The output should be:

```html
<div class="grid-container">
	<esi:include src="https://example/cookie_consent?locale=nb" />
</div>
```

### Actual behavior

Fully rendered HTML, which cannot be processed by the gateway.
```html
<div class="grid-container">
	<script type="text/javascript" src="/bundles/chcookieconsent/js/cookie_consent.js"></script>
	<div class="ch-cookie-consent ch-cookie-consent--dark-theme ch-cookie-consent--bottom">
		<div class="cookie__consent-description">
			<h3 id="cookie__consent-title">
[…]
```

### Steps to reproduce

1. Use something like the linked docs above:

```twig
<div class="grid-container">
	{{ render_esi(url('ch_cookie_consent.show_if_cookie_consent_not_set', { locale: app.request.locale })) }}
</div>
```

2. Enable Static Page Generation on a page with the `render_esi()` in the template.
3. Check the generated HTML.

**Comment by dvesh3** [comment]
Fixed by #14805

**Comment by NiklasBr** [comment]
Please reopen. Not fixed, just explained so that others experiencing this bug may not spend too much time.

**Comment by Gerhard-Kanzler** [comment]
Should be possible with this fix: https://github.com/pimcore/pimcore/pull/16012
There you can add the custom header into the static page generator. I add this for the ssi compatibility.

**Comment by NiklasBr** [comment]
@Gerhard-Kanzler I saw that, looks like it might fix this one as well, nice work!

I might get a chance to try the fix next week.

**Comment by brusch** [comment]
Fixed by #15983
