### ISSUE TITLE
[Bug]: Beta1 Install Core Bundle from an old Pimcore 10 -> users_permission_definitions

### ISSUE THREAD

**Issue by Gerhard-Kanzler** [pimcore/pimcore#14995]
### Expected behavior

Install the Static Routes / Newsletter Bundle should run without error on Update from a Pimcore 10.

### Actual behavior

When i install the Static Routes / Newsletter Bundle i get this error message: 
```bash
[ERROR] An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate 
         entry 'routes' for key 'PRIMARY'
```

The old `users_permission_definitions` Table in the DB has already the `routes` entry!

The solution should be in all Core Bundles to change the insert in an Update oder Insert/Update if the permission is already inside the table!

Maybe same problem in all other Core Bundles?

### Steps to reproduce

Insert this Content into a plain installed Pimcore 11 Beta 1 and install the Static Routes Bundle or Newsletter Bundle

```mysql
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('admin_translations', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('application_logging', 'Application Logger Bundle');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('assets', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('asset_metadata', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('bundle_ecommerce_back-office_order', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('bundle_ecommerce_pricing_rules', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('classes', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('classificationstore', 'Data Objects');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('clear_cache', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('clear_fullpage_cache', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('clear_temp_files', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('dashboards', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('documents', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('document_types', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('emails', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('fieldcollections', 'Data Objects');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('gdpr_data_extractor', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('glossary', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('http_errors', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('newsletters', 'Pimcore Newsletter Bundle');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('notes_events', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('notifications', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('notifications_send', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('objectbricks', 'Data Objects');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('objects', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('objects_sort_method', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('predefined_properties', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('quantityValueUnits', 'Data Objects');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('recyclebin', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('redirects', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('reports', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('reports_config', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('robots.txt', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('routes', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('seemode', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('seo_document_editor', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('share_configurations', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('sites', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('system_settings', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('tags_assignment', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('tags_configuration', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('tags_search', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('targeting', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('thumbnails', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('translations', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('users', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('web2print_settings', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('website_settings', '');
INSERT INTO pimcore.users_permission_definitions (`key`, category) VALUES ('workflow_details', '');
```

**Comment by mattamon** [comment]
Hey  @Gerhard-Kanzler,

thank you for your report! 

Seems like some migrations are missing. Every Bundle that worked on 10.5 should be marked as installed for 11.x
We ensure that by executing migrations like this one:
https://github.com/pimcore/pimcore/blob/11.x/bundles/CoreBundle/src/Migrations/Version20221222134837.php -> Static Routes
https://github.com/pimcore/pimcore/blob/11.x/bundles/CoreBundle/src/Migrations/Version20230406113010.php -> Newsletter.

Could you please check if the migrations did run through?

Another topic would be this:
https://pimcore.com/docs/pimcore/current/Development_Documentation/Development_Tools_and_Details/Migrations.html#page_Run-all-available-migrations-after -> we will add this topic to the upgrade and the preparation guide to make sure no one is missing it.

**Comment by mattamon** [comment]
@Gerhard-Kanzler we updated the docs accordingly:
https://github.com/pimcore/pimcore/blob/11.x/doc/23_Installation_and_Upgrade/07_Updating_Pimcore/12_V10_to_V11.md#migrations

Also added it in the Upgrade notes:
https://github.com/pimcore/pimcore/tree/11.x/doc/23_Installation_and_Upgrade/09_Upgrade_Notes -> [Migrations]

Please let me know if this solves your issue.

**Comment by mattamon** [comment]
I am closing the issue, since it should be resolved with the migrations :)

**Comment by solverat** [comment]
@mattamon: Still an issue, if you're using the `pimcore/admin-ui-classic-bundle` classic bundle, which does not get migrated during update.

Executing `bin/console pimcore:bundle:install PimcoreAdminBundle` will result in an exception:

```exception
[ERROR] An exception occurred while executing a query: SQLSTATE[23000]:
Integrity constraint violation: 1062 Duplicate entry 'admin_translations' for key 'PRIMARY'     
```
	
Quickfix: 
```
INSERT INTO settings_store (id,`scope`,`data`,`type`) VALUES ('BUNDLE_INSTALLED__Pimcore\\Bundle\\AdminBundle\\PimcoreAdminBundle','pimcore','1','bool')
```

**Comment by IronSean** [comment]
I get the error `An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'word_export' for key 'PRIMARY'` when I try to run the migrations

**Comment by NiklasBr** [comment]
@mattamon: Still an issue if you're using the `pimcore/admin-ui-classic-bundle`, which does not get migrated during update.

**Comment by APochmann** [comment]
I had the same issue as @solverat on executing `bin/console pimcore:bundle:install PimcoreAdminBundle`. It failed with error `1062 Duplicate entry 'admin_translations' for key 'PRIMARY'`.
It turned out that the installer of the bundle tried to INSERT this entry in `users_permission_definitions` table although it was already there (for whatever reason). I modified `addPermissions` function in `vendor/pimcore/admin-ui-classic-bundle/src/Installer.php` to check the value before inserting which worked for me:
```
    protected function addPermissions(): void
    {
        $db = \Pimcore\Db::get();

        // --- prevent 1062 Duplicate entry error -------
        $existingKeys = $db->fetchFirstColumn('SELECT ' . $db->quoteIdentifier('key') . ' FROM users_permission_definitions');
        // --- prevent 1062 Duplicate entry error --end--
		
        foreach (self::USER_PERMISSIONS as $permission) {
		
            // --- prevent 1062 Duplicate entry error -------
            if (in_array($permission, $existingKeys) {continue;}
            // --- prevent 1062 Duplicate entry error --end--
		
            $db->insert('users_permission_definitions', [
                $db->quoteIdentifier('key') => $permission,
                $db->quoteIdentifier('category') => self::USER_PERMISSIONS_CATEGORY,
            ]);
        }
    }

```

**Comment by IronSean** [comment]
This PR https://github.com/pimcore/pimcore/pull/16532#event-11776676161 was merged which updates the migration to be safer for running when the key already exists, Hopefully it will help those experiencing it still

**Comment by HageMaster3108** [comment]
Issue still observed in a web updated from pimcore 10 to pimcore 11.3.0
```[ERROR] An exception occurred while executing a query: SQLSTATE[23000]:
Integrity constraint violation: 1062 Duplicate entry 'admin_translations' for key 'PRIMARY'     ```

**Comment by HageMaster3108** [comment]
@APochmann Have created a PR with your suggested changes https://github.com/pimcore/admin-ui-classic-bundle/pull/602
