### ISSUE TITLE
[Bug]: Autoloading issue for navigation container in conjunction with OPCache

### ISSUE THREAD

**Issue by GALPR** [pimcore/pimcore#15970]
### Pimcore version

11.0.8

### Steps to reproduce

- Activate PHP OPCache extension
- Add a call to `new \Pimcore\Navigation\Container()` anywhere
- Reload the page where this call is executed multiple times (so that it is definitely cached by OPCache)
- This issue seems to occur since the following type-hint change: https://github.com/pimcore/pimcore/commit/83142b53cfd5a791e3c6167470a66336fd03da22#diff-6d072dd8e428eeff1dff129ad1056e39b8a7fdbf8273fa3aee2436a34d482ad4
- Removing the type-hints for the `Page` class again resolves this issue

### Actual Behavior

The page does not load anymore. I get the following exception logged in the php.log (formatted for readability):

```
Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\FatalError: 
"Error: During inheritance of Pimcore\Navigation\Container, while autoloading Pimcore\Navigation\Page: Uncaught Error: Class "Pimcore\Navigation\Container" not found in /var/www/html/vendor/pimcore/pimcore/lib/Navigation/Page.php:44 
Stack trace: 
#0 /var/www/html/vendor/symfony/error-handler/DebugClassLoader.php(293): include() 
#1 /var/www/html/vendor/pimcore/pimcore/lib/Navigation/Container.php(42): Symfony\Component\ErrorHandler\DebugClassLoader->loadClass('Pimcore\\Navigat...') 
#2 /var/www/html/vendor/symfony/error-handler/DebugClassLoader.php(293): include('/var/www/html/v...') 
#3 /var/www/html/src/Controller/DefaultController.php(19): Symfony\Component\ErrorHandler\DebugClassLoader->loadClass('Pimcore\\Navigat...') 
#4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(166): App\Controller\DefaultController->defaultAction(Object(Symfony\Component\HttpFoundation\Request)) 
#5 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) 
#6 /var/www/html/vendor/symfony/http-kernel/Kernel.php(197): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#7 /var/www/html/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) 
#8 /var/www/html/vendor/autoload_runtime.php(29): Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run() 
#9 /var/www/html/public/index.php(22): require_once('/var/www/html/v...') 
#10 {main}" at /var/www/html/vendor/pimcore/pimcore/lib/Navigation/Container.php line 42 {"exception":"..."} []
```

### Expected Behavior

The page should load as normal

**Comment by GALPR** [comment]
Any update / info on this?

**Comment by brusch** [comment]
@GALPR As you're experiencing the issue, could you please debug it and provide a PR with the fix? 
Thanks a lot in advance!

**Comment by GALPR** [comment]
The only fix I found that worked was to basically revert the linked change. Let me know if this is a viable solution and I will happily provide a PR. Here is the composer patch I am currently using:

```diff
diff --git a/lib/Navigation/Container.php b/lib/Navigation/Container.php
index 5a57e8b..250ce89 100644
--- a/lib/Navigation/Container.php
+++ b/lib/Navigation/Container.php
@@ -39,6 +39,9 @@ declare(strict_types=1);
 
 namespace Pimcore\Navigation;
 
+use RecursiveIterator;
+
 class Container implements \RecursiveIterator, \Countable
 {
     /**
@@ -109,7 +112,7 @@ class Container implements \RecursiveIterator, \Countable
      *
      * @throws \Exception if page is invalid
      */
-    public function addPage(Page|array $page): static
+    public function addPage($page): static
     {
         if ($page === $this) {
             throw new \Exception('A page cannot have itself as a parent');
@@ -189,7 +192,7 @@ class Container implements \RecursiveIterator, \Countable
      *
      * @return bool whether the removal was successful
      */
-    public function removePage(Page|int $page, bool $recursive = false): bool
+    public function removePage($page, bool $recursive = false): bool
     {
         if ($page instanceof Page) {
             $hash = $page->hashCode();
@@ -244,7 +247,7 @@ class Container implements \RecursiveIterator, \Countable
      *
      * @return bool whether page is in container
      */
-    public function hasPage(Page $page, bool $recursive = false): bool
+    public function hasPage($page, bool $recursive = false): bool
     {
         if (array_key_exists($page->hashCode(), $this->_index)) {
             return true;
@@ -508,7 +511,7 @@ class Container implements \RecursiveIterator, \Countable
      *
      * @throws \Exception
      */
-    public function current(): Page
+    public function current()
     {
         $this->_sort();
         $hash = key($this->_index);
@@ -551,7 +554,10 @@ class Container implements \RecursiveIterator, \Countable
         return $this->hasPages();
     }
 
-    public function getChildren(): ?Page
+    /**
+     * @return ?Page
+     */
+    public function getChildren(): ?RecursiveIterator
     {
         $hash = key($this->_index);
 ```

**Comment by LosHawlos** [comment]
I have seen this exact error message in Pimcore version 11.2.2 but I can not reliably reproduce the error.

**Comment by GALPR** [comment]
@LosHawlos Have you tried if my reproduction consistently leads to this issue for you?

**Comment by LosHawlos** [comment]
@GALPR I can reproduce it, but not reliably in a reduced test case.

Simply putting
`new \Pimcore\Navigation\Container()`
into a Controller does not always trigger the error, sometimes it simply works as expected.

It will be triggered when I load a page in Pimcore that does show a navigation using the Navigation Extension. But in the Pimcore Admin I see the strange effect that some pages show the navigation in editmode but fail in preview or frontend mode.

So there seems to be an outside factor related to triggering the error.

But: It seems to be related to the OPCache, because putting
`opcache_reset()`
into the Controller seems to fix it, but not on every page load.

BTW. I'm running Pimcore in Docker using the image "pimcore/pimcore:php8.2-max-v3".

**Comment by GALPR** [comment]
@LosHawlos Thanks for the info, definitely seems related. Do you also get the same fatal error in the php.log?

@brusch Any suggestions what an adequate fix could look like?

**Comment by brusch** [comment]
@GALPR for me it would be fine to revert the type-hints here, but we should then add the PhpDoc again as well and leave a comment why we're not using proper type-hints. 
Thanks!

**Comment by brusch** [comment]
This should be of course just a quick-fix we need further investigate what's the root-cause of this issue.

**Comment by GALPR** [comment]
@brusch Should I branch this off `11.x` or `11.2`?

**Comment by brusch** [comment]
@GALPR as others seem to be affected by this issue as well, I'd consider it as a bug fix and therefore it should go to `11.2` -  thanks!

**Comment by breakone** [comment]
@brusch can this be merged? is still not working.

**Comment by brusch** [comment]
fixed by #16989

**Comment by GALPR** [comment]
@brusch It seems like this issue still prevails even after the fix. I presume that all native types for `Page` need to be replaced with doc-types just as I've shown in my patch above.

**Comment by brusch** [comment]
@GALPR ok, thanks for the feedback - can you put that in a PR - thanks 😊

**Comment by GALPR** [comment]
@brusch Sure 🙂 Which branch should I target? 11.x oder 11.3?

**Comment by brusch** [comment]
@GALPR as I'd classify this as a bug, `11.3` please - thanks

**Comment by GALPR** [comment]
@brusch I wanted to do it now and just reread the whole conversation here beforehand. Seems like I already opened a PR for this and totally forgot about it 😄  
Would it be possible to reopen and merge this one? https://github.com/pimcore/pimcore/pull/17048  
I think the changes are still valid and mergable.

**Comment by brusch** [comment]
Ah, yes, sure, done! 😊👍

**Comment by GALPR** [comment]
@brusch I resolved the conflict but I am not sure what do to about the failing checks
