### ISSUE TITLE
[Bug]: Cannot save object with localizedfield and advanced object relation

### ISSUE THREAD

**Issue by foxgreek** [pimcore/pimcore#17878]
### Pimcore version

11.4.2

### Steps to reproduce

1. Create class definitions Test and TestRelation in pimcore demo:
[class_Test_export.json](https://github.com/user-attachments/files/17967437/class_Test_export.json)
[class_TestRelation_export.json](https://github.com/user-attachments/files/17967438/class_TestRelation_export.json)

2. Create Test Object

3. Create Test Relation

4. Drag&Drop Test Object, add custom price

5. save twice (pressing CMD+S or press Save and Publish twice)

### Actual Behavior

You will get following error:
![Image](https://github.com/user-attachments/assets/b00c9c0f-a529-4cfc-8f9b-1d11bf6dd4d3)

### Expected Behavior

The Object should be saved without any errors

**Comment by kingjia90** [comment]
Resolved by https://github.com/pimcore/pimcore/pull/17133

**Comment by foxgreek** [comment]
Hi @kingjia90 I tried your cherry pick in my local environment, but it still throws the same error on save & publish.
