### ISSUE TITLE
[Objects] Classes: possibility to define table identifier (replacing the current class-ID)

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#2916]
- ID gets alphanumeric and can be manually specified (on creation) 
- we cannot automatically use the class name due to the 64 characters limit on table names of MySQL

**Comment by dpfaffenbauer** [comment]
Whats the reason for that? I don't see any advantage in that? And this could be eventually break things as well.

**Comment by fashxp** [comment]
getting rid of auto-increment class ids -> having same table names on all stage instances. 
this is a thing that is requested quite a lot by you guys

**Comment by dpfaffenbauer** [comment]
as thought, this is not backward compatible.

```
Exception: Class id is null in /home/travis/build/coreshop/CoreShop/pimcore/models/DataObject/ClassDefinition.php:162
```

when using class installer like:

```
$class = DataObject\ClassDefinition::create();
$class->setName($className);
$class->setUserOwner(0);

DataObject\ClassDefinition\Service::importClassDefinitionFromJson($class, $json, true);
```

**Comment by dpfaffenbauer** [comment]
the reason for this is quite clear, you removed the auto-increment from the classes table and now no ID gets generated. This is quite a serious issue you produced here, a lot of plugins use this way of installing classes and this change now broke all of them. This is not tested well and not thought thru well.

**Comment by podarcis** [comment]
@dpfaffenbauer 

> And regarding stages: I always copy production db to dev db when I have to test things or a lot of data changed thru imports and stuff like that. Just to have the same data in both stages, that way you have the same table-names anyway as well.

Consider a project already being in production and in dev there's two new classes. When using an automatic deployment mechanism (deployment:classes-rebuild -c) the order of the class ids might differ. I agree that it's not hard to lookup the table name, however same table names prevent confusion and mistakes during manual administration.

And for projects also versioning the Pimcore object class PHP files in SCM instead of just the definition files (yes, this might not be a good idea at all) the automatic deployment can even screw up things, as the class ids created differ from the versioned class ids.

However, I agree that this change should be fully BC.

**Comment by weisswurstkanone** [comment]
fixed by generating a ID if not explicitely set.

build 271

**Comment by dpfaffenbauer** [comment]
Still not fixed, following scenario still fails:

```php
$classDefinition = new ClassDefinition();
$classDefinition->setName('foo');
$classDefinition->setLayoutDefinitions(
    json_decode('')
);
$classDefinition->save();

$classDefinition = ClassDefinition::getByName('foo');
$classDefinition->delete();

$classDefinition2 = new ClassDefinition();
$classDefinition2->setName('bar');
$classDefinition2->setLayoutDefinitions(
    json_decode('')
);
$classDefinition2->save();

$classDefinition3 = ClassDefinition::getByName('bar');

echo null === $classDefinition3 ? 'null' : $classDefinition3->getName();
```

Reason should be quite clear as well, it creates the first Class 'foo' with ID 1, then deletes it and creates class 'bar' with ID 1, pimcore still keeps class 'foo' in cache and tries to update that one -> nothing to update though, cause it has already been deleted, so class 'bar' never gets created.

Issue belongs to this case, since this could not have happened before, cause the ID for 'bar' would have been 2.

**Comment by dpfaffenbauer** [comment]
all of my tests are failing cause of this, only quick fix is to clear runtime cache before each test, which is not a suitable solution.

Why don't your tests fail? Your tests should also have the same issue when creating and deleting classes.

**Comment by dpfaffenbauer** [comment]
BTW: Have you also thought about class-definition files and the new identifier? Don't think that it would work.... Where should the definition file get the class-identifier from?

**Comment by brusch** [comment]
@dpfaffenbauer nothing changes regarding the definition files .. shouldn't be a problem at all.

**Comment by dpfaffenbauer** [comment]
@brusch And that is exactly the issue, following scenario:

 - I create a new class on my dev env with class-id: 'foo'
 - I check in the definition file
 - run my deployment (which runs `pimcore:deployment:classes-rebuild -c -n`)
 - Class will get next available integer ID instead of 'foo', cause the definition file has no clue about 'foo'

**Comment by brusch** [comment]
@dpfaffenbauer Sorry, you're absolutely right ;) 
88056f39cc04f4d113406454f9640bf6c062abeb should fix the issue. 

In future, when someone wants to force auto-increment on deployment, it is necessary to strip the `id` property out of the definition file before checking it in.

**Comment by dpfaffenbauer** [comment]
You can't be serious? That is another BC break, you cannot expect from a dev to always strip out the ID, some will forget about that and that runs into other errors then.

**Comment by dpfaffenbauer** [comment]
the whole point of not having the ID was that if two devs work on the same project and they do a deployment, Pimcore handles the class-id for them.

**Comment by brusch** [comment]
The whole point was to avoid ID conflicts, since it was not possible to manually specify the ID. That's possible as of now, so there's no reason anymore to strip the ID out of the definition file, is it?

**Comment by dpfaffenbauer** [comment]
its not, cause this feature definitely has impact on current installations and current deployments. 

Following scenario:
 - Dev 1 creates class Product with auto-id. Class gets ID1
 - Dev 2 creates class Category with auto-id. Class gets ID1

Deployment broken cause 2 classes have the same ID. 

Scenario I mentioned yesterday: broken cause there is no runtime cache invalidation, easy fix, wouldn't be too hard though.

Sure, having the possibility to custom define a table-name sounds great, but:
 1. either force it for every object and drop auto id support totally -> this mix and match causes issues as well
 2. provide a BC layer that doesn't break every use-case: For example by introducing a new field into the classes table and mark the old one deprecated and remove it in 6.0
 3. add more test-cases to your tests to find this issues and testBC support.

**Comment by brusch** [comment]
> Following scenario:
Dev 1 creates class Product with auto-id. Class gets ID1
Dev 2 creates class Category with auto-id. Class gets ID1

Merge conflict, needs to be solved and can be solved. If they agree to use alphanumeric identifiers they can get the risk of conflicts to a minimum. 

> either force it for every object and drop auto id support totally -> this mix and match causes issues as well
  
Which issues for example (in really very common use cases)? 

> provide a BC layer that doesn't break every use-case:
  
We don't break **every** use case, that's simply not the truth. There's a BC layer that supports both, auto-increment and manual IDs, but in point 1 you're also not happy with that ;)

**Comment by dpfaffenbauer** [comment]
> Merge conflict, needs to be solved and can be solved. If they agree to use alphanumeric identifiers they can get the risk of conflicts to a minimum.

What merge conflict? Two different classes with the same ID, there is no merge at all.

> Which issues for example (in really very common use cases)?

You don't think that testing is a very common use case? That issue happens with my tests.

> We don't break every use case, that's simply not the truth. There's a BC layer that supports both, auto-increment and manual IDs, but in point 1 you're also not happy with that ;)

Yes, cause that BC layer doesn't work properly.

If you would get rid of the auto-increment and force new classes to always define a table-identifier, issue 1 and 2 would never happen. Old classes then would have the table-identifier as their ID, so there is BC as well. What do you think about that? There also needs to be a migration which creates all class-definitions with the class-id in it.

**Comment by brusch** [comment]
- Well, like a merge conflict is what I meant ;) 
- Tests are not application code, application code continues to work without any issues

We don't force a BC break, because of bundles etc. (like you mentioned already earlier) - so it makes sense to keep the BC behavior imho. 

Any other options on that? :)

**Comment by dpfaffenbauer** [comment]
Nothing more to say then... I am sure this makes some troubles elsewhere but anyway... Like Bulk Import, a guy from gitter had that problem. I didn't tested it though.

**Comment by weisswurstkanone** [comment]
From now on, the class id from the bulk file will be respected as well.

**Comment by Cruiser13** [comment]
This broke Objects with Metadata fields on updating from Pimcore 5.2.2 to 5.4.3 on our installation. The allowed class has been gone rendering errors in editing the objects itself. We had to set the allowed class again but all relation data has been lost.
