### ISSUE TITLE
Href Editable Tag denies dnd when subtype restrictions are set

### ISSUE THREAD

**Issue by simonrainer** [pimcore/pimcore#361]
Reproduce:

Create a Href Editable like:

    $this->href('no-result-doc', [
    'types' => ['document'],
    'subtypes' => ['snippet']])

If you try to drop a Snippet at the Href it won't be accepted. Removing the subtype restriction circumvents the problem.

Assumed area of bug:

href.js (ca line 159):

    //subtype check  (folder,page,snippet ... )
            if (this.options.subtypes) {
                found = false;
                var typeKeys = Object.keys(this.options.subtypes);
                for (var st = 0; st < typeKeys.length; st++) {
                    for (i = 0; i < this.options.subtypes[typeKeys[st]].length; i++) {
                        if (this.options.subtypes[typeKeys[st]][i] == data.node.attributes.type) {
                            found = true;
                            break;
                        }
                    }
                }
                if (!found) {
                    return false;
                }
            }

**Comment by weisswurstkanone** [comment]
fixed in build 3588

**Comment by Senkstyla** [comment]
the bug still exists in Version: 4.0.0-RC1 Build: 3691

**Comment by niwann** [comment]
it seems like the subtype bug still exists in Version: Version: 4.0.0 Build: 3777

**Comment by brusch** [comment]
fixed by 6a1b3ad4de90375132dac013e930112ae8a11808
