### ISSUE TITLE
[ecommerce] On ES6, filters based on number return errors.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#4090]
Hello,

We are trying the ecommerce to switch from mysql to elasticsearch 6.
Indexation work great, filters too, but the two numeric filters send errors.
Using mysql for the same filters there was no errors.

Config of the index for ES6 for this field is:

```
                    number_unit:
                        type: double
                        options:
                            store: true
                        filter_group: double
```

We tried with different type (integer, float, long) same errors are returned.

Using "Filter Numberrange Selection", we get the following error on the frontend during generation of the html for the filter:

![image](https://user-images.githubusercontent.com/9025839/54555168-765a0f80-49b6-11e9-819e-9058cdd5163b.png)

Using "Filter Numberrange", we get this one:

![image](https://user-images.githubusercontent.com/9025839/54555258-a2759080-49b6-11e9-95c8-069266ee0e8c.png)

Thanks.

**Comment by fashxp** [comment]
numberrangeselection was already fixed here: https://github.com/pimcore/pimcore/pull/4041

**Comment by Yivan** [comment]
@fashxp Thanks ! I just added a comment to the commit (https://github.com/pimcore/pimcore/commit/ac8a3644f02ba609447e7f7806ae13fe9dd5c244), as it is not fully fixed (in case input field from/to are sent with empty string (empty html input fields).

Thanks.

**Comment by fashxp** [comment]
added the additional checks ... you also could provide a PR, would speedup things ;-) 

thx anyway!
