### ISSUE TITLE
Changes related to #4555 broke cache warmup.

### ISSUE THREAD

**Issue by das-peter** [pimcore/pimcore#4709]
The changes related to #4555 seem to have broken the cache clearing / warming (`bin/console cache:clear`).
   1. https://github.com/pimcore/pimcore/commit/8c41e8155805b16dc2d6c6aecb77e2ad871f452c
   2. https://github.com/pimcore/pimcore/commit/4f7725c70586767fc5ddd7e0fb8399adffd0be0f#diff-ff0c921492cef999788fd76dcb807a22R306

The second change seems to trigger following error:
```
Warning: Uncaught ErrorException: Warning: require(/var/www/pimcore/var/cache/in_/ContainerLEnsbem/removed-ids.php): failed to open stream: No such file or directory in /var/www/pimcore/var/cache/int/ContainerLEnsbem/appAppKernelIntDebugContainer.php:634
Stack trace:
#0 /var/www/pimcore/var/cache/int/ContainerLEnsbem/appAppKernelIntDebugContainer.php(634): require()
#1 /var/www/pimcore/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(161): ContainerLEnsbem\appAppKernelIntDebugContainer->getRemovedIds()
#2 /var/www/pimcore/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(392): Symfony\Component\DependencyInjection\Container->set('container.env_v...', Object(Symfony\Component\DependencyInjection\ServiceLocator))
#3 /var/www/pimcore/var/cache/int/ContainerLEnsbem/appAppKernelIntDebugContainer.php(1259): Symfony\Component\DependencyInjection\Container->getEnv('trim:file:DB_US...')
#4 /var/www/pimcore/vendor/symfony/symfony/src/Symfony/Component/DependencyInjectio in /var/www/pimcore/var/cache/int/ContainerLEnsbem/appAppKernelIntDebugContainer.php on line 634

Fatal error: ContainerLEnsbem\appAppKernelIntDebugContainer::getRemovedIds(): Failed opening required '/var/www/pimcore/var/cache/in_/ContainerLEnsbem/removed-ids.php' (include_path='/var/www/pimcore/vendor/pear/archive_tar:/var/www/pimcore/vendor/pear/console_getopt:/var/www/pimcore/vendor/pear/net_url2:/var/www/pimcore/vendor/pear/pear-core-minimal/src:/var/www/pimcore/vendor/pear/pear_exception:.:/usr/local/lib/php') in /var/www/pimcore/var/cache/int/ContainerLEnsbem/appAppKernelIntDebugContainer.php on line 634
```

It seems like the used `\Pimcore\Db::get()` in `\Pimcore::isInstalled()` doesn't work properly during a cache warmup.
During a cache warmup the return values of `Kernel->getCacheDir()` and `Kernel->getContainer()->getParameter('kernel.cache_dir')` are incosistent.
Symfonys UPGRADE-4.0.md says:
>  The `getCacheDir()` method of your kernel should not be called while building the container.
>  Use the `%kernel.cache_dir%` parameter instead. Not doing so may break the `cache:clear` command.

The problem seems to be that the Environment used in `\Pimcore\Db::get()` will try to access the temporary warmup directory which in the meantime already has been moved into place of the regular cache.
This is because the warmup is completed before our shutdown handler runs and the environment isn't cleaned up.

The only thing I could think of for the moment to work around this is a condition like this:
```php
        // Check if this is a cache warming run and if this runs on an installed instance. If this is a cache warmup
        // we can't use self::isInstalled() as it will refer to the wrong caching dir.
        if (self::getKernel()->getCacheDir() === self::getContainer()->getParameter('kernel.cache_dir') && self::isInstalled()) {
```
So `bin/console cache:clear --no-warmup` will go into the condtion while `bin/console cache:clear` will skip it.

**Comment by brusch** [comment]
@das-peter  This PR unfortunately causes issues when the cache dir is a symlink. 
I'm wondering anyway why this exception isn't caught by the try/catch here: https://github.com/pimcore/pimcore/blob/89a989319440a6704856899da54a95a52ee2c80f/lib/Pimcore.php#L150

Could you maybe provide a bit more information on that? At least how to reproduce the error above, because on my test-env I wasn't able to reproduce it. 
Otherwise I'd have to revert this PR. 
Thanks a lot!

**Comment by dvesh3** [comment]
resolved by #6627

**Comment by cancan101** [comment]
I am still seeing this error in 10.6 when cache warming. the [`\Pimcore::collectGarbage();` line](https://github.com/pimcore/pimcore/blob/v10.6.9/lib/Cache/Tool/Warming.php#L129) is causing:
```
Error: Failed opening required '/var/www/pimcore/var/cache/prod/ContainerFwaKMei/removed-ids.php' (include_path='/var/www/pimcore/vendor/pear/net_url2:.:/usr/share/php')
#15 /var/cache/prod/ContainerFwaKMei/App_KernelProdContainer.php(916): ContainerFwaKMei\App_KernelProdContainer::getRemovedIds
#14 /vendor/symfony/dependency-injection/Container.php(159): Symfony\Component\DependencyInjection\Container::set
#13 /vendor/pimcore/pimcore/lib/Cache/RuntimeCache.php(195): Pimcore\Cache\RuntimeCache::clear
#12 /vendor/pimcore/pimcore/lib/Helper/LongRunningHelper.php(115): Pimcore\Helper\LongRunningHelper::cleanupPimcoreRuntimeCache
#11 /vendor/pimcore/pimcore/lib/Helper/LongRunningHelper.php(74): Pimcore\Helper\LongRunningHelper::cleanUp
#10 /vendor/pimcore/pimcore/lib/Pimcore.php(227): Pimcore::collectGarbage
```
