### ISSUE TITLE
Versioning performance with a lot of relationships

### ISSUE THREAD

**Issue by belendel** [pimcore/pimcore#5813]
Hi,

It seems the recursive DeepCopy used when saving a new version has a serious performance impact when you have a lot of relationships. The following is a blackfire profile for a batch edit of 25 objects:

https://blackfire.io/profiles/9902f36c-0857-4511-ac3a-54bf25e10a29/graph

When I make a shallow copy it's significantly faster. Is there any reason for traversing all of the related objects? Of course direct relationships have to be included because they are shown in the version tab but any deeper than this is not included in the version data anyway.

**Comment by brusch** [comment]
Related to #4154

**Comment by weisswurstkanone** [comment]
Can you confirm that you are on the latest release? With 6.1.0 we added a ReplaceFilter which optimize the whole stuff.

**Comment by weisswurstkanone** [comment]
Not directly related but for completeness: https://github.com/pimcore/pimcore/pull/5858

**Comment by brusch** [comment]
With #4667 the issue with many relations should be resolved. 
#5858 brings also some additional improvements, especially for Data Objects. 

One thing that can be further improved is that we're setting `children` to null, before doing the deep copy.

**Comment by weisswurstkanone** [comment]
Not setting them to null will still not cause that they get traversed, right?
Reason is that they are treated just like a relation (replaced with an ElementDescriptor)

**Comment by kubaplas** [comment]
Hi,
I can contribute my profile also: https://blackfire.io/profiles/8252677b-5d00-406f-a1f1-53f8bbe2066a
Somewhat complex data model with classification store, but most of the fields are empty.
Using dev-master (80b6afa115a2d174b64cc9f69b2a9426d42173ef)

**Comment by weisswurstkanone** [comment]
see https://github.com/pimcore/pimcore/pull/5917

**Comment by belendel** [comment]
> Can you confirm that you are on the latest release? With 6.1.0 we added a ReplaceFilter which optimize the whole stuff.
> 
> See #4667

This was tested with 6.4.0. I believe it still traverses the whole tree even with the ReplaceFilter. I can  do a new profile with the latest version if you want.

**Comment by weisswurstkanone** [comment]
thx!

**Comment by kubaplas** [comment]
@weisswurstkanone I think that #5917 is not related to this task - I've made profiles for #5917 with versioning disabled.

**Comment by weisswurstkanone** [comment]
It is related to the general performance of versioning :-) Just wanted to link them together.

**Comment by weisswurstkanone** [comment]
not directly related to what you describe but may help as well:
https://github.com/pimcore/pimcore/pull/5922

**Comment by weisswurstkanone** [comment]
@belendel any new findings ?

**Comment by belendel** [comment]
@weisswurstkanone I will upgrade our pimcore installation tomorrow and run some new profiles and try to look into the issue a bit myself. I will keep you updated.

**Comment by weisswurstkanone** [comment]
great, thanks a lot!

**Comment by belendel** [comment]
Good morning!

I did a bit of investigation and it seems the issue wasn't actually in the relationships, but in the Pimcore\Model\DataObject\Concrete::o_class property. This is an object of type Pimcore\Model\DataObject\ClassDefinition.

The class definition I did my tests with has a large amount of fields, including a classification store. The performance didn't improve after updating to version 6.5.3. I ran a profile on a custom route where I update the same object 3 times with a random value. You can find the first profile here:

https://blackfire.io/profiles/ef60826a-3349-405e-b8aa-e8e9fa167cd9/graph

I assume the ClassDefinition doesn't need to be included in the copy since it isn't used for the version data. So I added a SetNullFilter like this:

```php
$copier->addFilter(new \DeepCopy\Filter\SetNullFilter(), new \DeepCopy\Matcher\PropertyTypeMatcher('Pimcore\Model\DataObject\ClassDefinition'));
```

Profile after changes:

https://blackfire.io/profiles/eb229b13-336c-4c10-8862-19eb0c122055/graph

This sped up the saving almost 4 times. Let me know if you have any questions!

**Comment by weisswurstkanone** [comment]
Thanks for investigating and sharing 👍 

I believe we already adressed this. Milestone is 6.6

See https://github.com/pimcore/pimcore/pull/5922

Can you confirm if this yields the same results?

**Comment by belendel** [comment]
Same issue:

https://blackfire.io/profiles/9760fdda-43d1-4a0a-8e33-cd92e67b0222/graph

I am not as familiar with the code as you guys, but I don't see how this change will filter out the $o_class property. 

1. The PimcoreClassDefinitionMatcher only matches when the class property is found as FieldDefinition on the ClassDefinition. I assume the actual $o_class property is not a FieldDefinition.
2. Data\CustomVersionMarshalInterface isn't actually implemented anywhere:https://github.com/pimcore/pimcore/search?q=CustomVersionMarshalInterface&unscoped_q=CustomVersionMarshalInterface

Is there a reason to not just set the $o_class property to null? I assume it's not necessary for the versioning.

**Comment by weisswurstkanone** [comment]
Nulling it out is already done via (since 6.5.2)
https://github.com/pimcore/pimcore/pull/5858

#5922 then makes sure that o_class doesn't get filled in again.

**Comment by belendel** [comment]
I think the problem is in DeepCopy\DeepCopy::copyObject()

You will find the following code:

```php
foreach (ReflectionHelper::getProperties($reflectedObject) as $property) {
            $this->copyObjectProperty($newObject, $property);
        }
```

It does this on the original object. Not the cloned object. Setting it to null in the __clone() doesn't solve the issue in the case.

**Comment by weisswurstkanone** [comment]
Good catch!

**Comment by dpfaffenbauer** [comment]
Shouldn't a Filter work to not copy over o_class?

**Comment by weisswurstkanone** [comment]
That is what he suggested

**Comment by dpfaffenbauer** [comment]
oops, sorry, missed that.

**Comment by weisswurstkanone** [comment]
Create a PR 
https://github.com/pimcore/pimcore/pull/5981

Thanks @belendel

**Comment by belendel** [comment]
Great! Thanks a lot :+1:

**Comment by brusch** [comment]
@belendel @weisswurstkanone #5981 fixed the issue, right? So we can close this ticket? 
Thanks for your feedback!

**Comment by weisswurstkanone** [comment]
@belendel ok from your side ?

**Comment by belendel** [comment]
Sorry, missed your message. Everything is ok now! You can close the ticket.

**Comment by weisswurstkanone** [comment]
thx @belendel
