### ISSUE TITLE
Pimcore Update from 3.1.1 to 4.0 fails on Windows

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/pimcore#600]
The built-in pimcore updater fails on Windows (Windows Server 2012 and 2012 R2 confirmed) with the following error message:

> Install of update fails, see debug.log for more details.
> Error-Message:
> Warning: copy(C:\pimcore-domain/vendor/zendframework/zendframework1/library/Zend/Service/WindowsAzure/CommandLine/Scaffolders/DefaultScaffolder/resources/PhpOnAzure.Web/resources/WebPICmdLine/Microsoft.Web.Deployment.dll): failed to open stream: Invalid argument in C:\pimcore-domain\pimcore\lib\Pimcore\Update.php on line 269
> Warning: copy(C:\pimcore-domain/vendor/zendframework/zendframework1/library/Zend/Service/WindowsAzure/CommandLine/Scaffolders/DefaultScaffolder/resources/PhpOnAzure.Web/resources/WebPICmdLine/Microsoft.Web.PlatformInstaller.UI.dll): failed to open stream: Invalid argument in C:\pimcore-domain\pimcore\lib\Pimcore\Update.php on line 269
> Warning: copy(C:\pimcore-domain/vendor/zendframework/zendframework1/library/Zend/Service/WindowsAzure/CommandLine/Scaffolders/DefaultScaffolder/resources/PhpOnAzure.Web/resources/WebPICmdLine/Microsoft.Web.PlatformInstaller.dll): failed to open stream: Invalid argument in C:\pimcore-domain\pimcore\lib\Pimcore\Update.php on line 269
> {"success":true}

Looks like the Zend Framework can not be copied properly by composer. The issue is known and may be fixed in the ZF1 repository / composer repository here: https://github.com/zendframework/zf1/issues/174

A rollback of the pimcore update seems to fail in this case. A backup of the 3.1.1 pimcore installation must be manually established again.

**Comment by brusch** [comment]
Excluded %/WindowsAzure/CommandLine/Scaffolders/% from the updater, seems to be the only method of getting around this issue. 

Should work now :)

**Comment by Cruiser13** [comment]
The issue is back with the update 4.1.1. Since updates are run by composer now I'd guess that we'd need something like "exclude-from-classmap": ["%/WindowsAzure/CommandLine/Scaffolders/%"] in the composer.json ?

**Comment by brusch** [comment]
I don't know a way of doing this with composer ...

**Comment by Cruiser13** [comment]
@brusch adding the line to my composer.json file let me do the update on 4.1.1:

`    "autoload": {
        "psr-4": {
            "Pimcore\\Model\\Object\\": "website/var/classes/Object",
            "Pimcore\\Model\\": "pimcore/models",
            "Pimcore\\": "pimcore/lib/Pimcore"
        },
        "exclude-from-classmap": [
            "%/WindowsAzure/CommandLine/Scaffolders/%"
        ]
    },`

This worked for me on two installations so far. Live updater finished without errors after adding this. Manual composer update of pimcore worked with that addition too. Further info on Composer side can be found here: https://getcomposer.org/doc/04-schema.md#exclude-files-from-classmaps

**Comment by brusch** [comment]
Thanks - integrated!

**Comment by Cruiser13** [comment]
Thank you @brusch but maybe that was too fast. My third testing platform failed to update properly using the new composer.json. The live updater completed but showed this error:
![pimcore-composer-update](https://cloud.githubusercontent.com/assets/2771909/16005322/ec7172b4-3166-11e6-9b2a-deb765087eed.png)
Version was 4.1.1 anyway though. 
Manually running **composer update nothing** failed while running **composer update** succeeded, both installed/updated some more packages (sebastian... and others). I'm not sure on which state the updated system is at the moment and I'll do a rollback on this specific installation. The other two seem to be working fine.

**Comment by brusch** [comment]
What was the error message of composer update nothing ?



-------- Ursprüngliche Nachricht --------
Von: Lennart Sauter <notifications@github.com>
Datum: 13.06.16 13:03 (GMT+01:00)
An: pimcore/pimcore <pimcore@noreply.github.com>
Cc: Bernhard Rusch <Bernhard.Rusch@elements.at>, Mention <mention@noreply.github.com>
Betreff: Re: [pimcore/pimcore] Pimcore Update from 3.1.1 to 4.0 fails on Windows (#600)


Thank you @brusch<https://github.com/brusch> but maybe that was too fast. My third testing platform failed to update properly using the new composer.json. The live updater completed but showed this error:
[pimcore-composer-update]<https://cloud.githubusercontent.com/assets/2771909/16005322/ec7172b4-3166-11e6-9b2a-deb765087eed.png>
Version was 4.1.1 anyway though.
Manually running composer update nothing failed while running composer update succeeded, both installed/updated some more packages (sebastian... and others). I'm not sure on which state the updated system is at the moment and I'll do a rollback on this specific installation. The other two seem to be working fine.

-

**Comment by brusch** [comment]
What was the error message of composer update nothing ?

**Comment by brusch** [comment]
I'm not sure if we can do anything further, since this is caused by the 260 characters path limitation of windows, and zf1 is referenced in composer.json, see also: 
https://github.com/zendframework/zf1/issues/174 

So this needs do be addressed either by the ZF or by the anyone who is using it on Windows -> see also https://github.com/zendframework/zf1/issues/356#issuecomment-65703023
If there's anything further we can do, let me know. :)

**Comment by brusch** [comment]
so the `exclude-from-classmap` has basically no effect and we can remove it again, right?

**Comment by Cruiser13** [comment]
I'm in the progress of the rollback of the system. I'll reattempt the steps to get the composer update nothing error message again and debug this further.
There must be a proper way around this issue, otherwise Pimcore will be no longer working on windows installations (at least not in subfolders) with version 4.1.

I'm not sure if exclude-from-classmap has the proper effect since I was able to update two installations with this change. I need to check them for integrity though. Looks like some files might not have been copied.

**Comment by brusch** [comment]
Ok, thanks! 
But again, this isn't a pimcore problem at all ... please try the same in an empty directly with `composer require zendframework/zendframework1` and you will encounter the same problem :)

**Comment by Cruiser13** [comment]
You are right @brusch but this issue makes pimcore stop working because of an issue with a dependency.
Exclude from Classmap can definately be removed because the files are not added to classmap anyway, they are DLLs. Sorry, not that familiar with Composer yet. 

I'm not sure if it could work using archive exclude:
https://getcomposer.org/doc/04-schema.md#archive
Maybe something like this:

`	"archive": {
        "exclude": [ "/WindowsAzure" ]
    }`

Please do not yet include it, I didn't have a chance to test it so far. But it seems that this would be the right command to exclude the folder in this case. Not sure if we can force that on zendframework from the pimcore composer.json though. Maybe anybody who is more familiar with composer could check that?

**Comment by brusch** [comment]
Thanks for your answer. 
Let me know if you have a solution, then we'll include it in the core distribution.
