### ISSUE TITLE
Upload PDF as asset and generate Thumbnail-Preview does not work anymore

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#668]
Exception: Call to undefined method getWidth in class Pimcore\Model\Asset\Document in XXX/pimcore/lib/Pimcore/Model/AbstractModel.php:266

**Comment by solverat** [comment]
**this is urgent!** since we updated to release 4.1.2 the asset uploader does not work anymore.

![bildschirmfoto 2016-06-16 um 18 01 32](https://cloud.githubusercontent.com/assets/700119/16123756/737130c4-33ec-11e6-8d7c-1dc15cb30e38.png)

**Comment by ctrl-s** [comment]
We confirm, that there is an **urgent** issue with document thumbnails!
Methods getWidth and getHeight are missing.

**Comment by brusch** [comment]
Fix is on the way -> release planned for tomorrow.

**Comment by fashxp** [comment]
fixed in build 3856

**Comment by solverat** [comment]
**urgent:** the problem still exists. try to upload an asset on demo.pimcore.org.

**Comment by fashxp** [comment]
adding assets via d&d works perfectly fine. 
so this is another problem. please add an seperate issue. thank you.
