### ISSUE TITLE
Login as this user not working with custom admin login entry point

### ISSUE THREAD

**Issue by kjkooistra-youwe** [pimcore/pimcore#6909]
### Expected behavior
Logging in as the user when opening `Login as this user` link.

### Actual behavior
Server returned a 404 error.

### Steps to reproduce
- [Configure a custom admin entry point](https://pimcore.com/docs/6.x/Development_Documentation/Development_Tools_and_Details/Custom_Admin_Login_Entry_Point.html)
- Open a user, click the `Login as this user in a different browser` button and copy the link
- Paste the link into a private window of another browser, simulating opening the environment for the first time

Replacing '/admin' in the link with the custom login entry point name results in a Pimcore page not found error (the one with the unicorn).

### Workaround
Open the custom admin login entry point first. It will redirect to /admin and this state is stored it in the session it seems. The link will open correctly now.

**Comment by kjkooistra-youwe** [comment]
Similar to issue https://github.com/pimcore/pimcore/issues/6856

**Comment by brusch** [comment]
fixed by #6910

**Comment by debanshu411** [comment]
I upgraded Pimcore to 6.7.0 but the issue still persists do I have to do any other changes to my application.

**Comment by dvesh3** [comment]
@debanshu411 It works on 6.7.0. No changes required if you are using exact route name `my_custom_admin_entry_point` from documentation. https://pimcore.com/docs/6.x/Development_Documentation/Development_Tools_and_Details/Custom_Admin_Login_Entry_Point.html
