### ISSUE TITLE
Grid rows not equal in Grid View

### ISSUE THREAD

**Issue by Hbitvof** [pimcore/pimcore#6918]
Hi,

When there is an image in the grid view and a lock at a specific column the column's don't line up properly when scrolling:

Here is an example:

![image](https://user-images.githubusercontent.com/41229269/89561906-7bbd3180-d819-11ea-9e14-faf84274c635.png)

This is getting worse the more you scroll. We only see this when using the image column in grid view. When this column isn't shown everything is working normally.

**Comment by dvesh3** [comment]
@Hbitvof you mean when there are rows without image in-between?

**Comment by Hbitvof** [comment]
@dvesh3 that's correct. When there is no row with images in grid view everything is working normally but with images it is not.

**Comment by dvesh3** [comment]
ExtJS bug https://forum.sencha.com/forum/showthread.php?303854-Locked-grid-Problem-row-height-with-multi-line-cells will be fixed in next major version with ExtJS 7 #6922

**Comment by dvesh3** [comment]
Fixed by #6922

**Comment by Hbitvof** [comment]
This problem is still not fixed. We run the latest version of Pimcore and still the same problem when scrolling down:

![image](https://user-images.githubusercontent.com/41229269/169643312-b7a774fa-864e-4e6d-bca1-acc4aa2933c3.png)

**Comment by Hbitvof** [comment]
This bug is not fixed in PimCore 10.x, please reopen this issue.

**Comment by brusch** [comment]
@Hbitvof there is already a follow up ticket, it doesn't help to spam here. Thanks. 
Please also consider our contributing guidelines: 
https://github.com/pimcore/pimcore/blob/10.x/CONTRIBUTING.md#contributing-to-pimcore

Especially: 
> It's also important for us to make clear that **we're not working for you or your company**, but we enjoy to work together to solve issues or improve the product.

Thanks 😊

**Comment by Hbitvof** [comment]
> @Hbitvof there is already a follow up ticket, it doesn't help to spam here. Thanks. Please also consider our contributing guidelines: https://github.com/pimcore/pimcore/blob/10.x/CONTRIBUTING.md#contributing-to-pimcore
> 
> Especially:
> 
> > It's also important for us to make clear that **we're not working for you or your company**, but we enjoy to work together to solve issues or improve the product.
> 
> Thanks 😊

Apologies, it is was not my intention to spam here or being rude but I thought it was smart to reopen this issue, because this has all the information about the problem. I understand this is not possible? I only use Github for bug reports and I am not a developer so I don't know the exact working and rules.
