### ISSUE TITLE
Deleting a brick does not delete its content in tmp_store

### ISSUE THREAD

**Issue by roland4432** [pimcore/pimcore#8122]
# Bug Report

### Expected behavior
Deleting a brick should also delete its content. (or is this an intended feature as a "backup"?)

### Actual behavior
When you delete a brick and and add the same type at the same position the former content will be restored.

The update method of each brick writes contents to the tmp_store table. Deleting and adding a brick will trigger a reload from the tmp_store table. Conclusion is therefore, that the delete does not remove the content from the tmp_store and then gets the content from this table when you readd the same brick at the same index.

### Steps to reproduce

Add a page. Add a brick (e.g. a Text-Brick). Enter some text. Delete the brick and readd the same brick type at the same position.
=> Text from removed brick will reappear.

**Comment by passioneight** [comment]
This also holds true for `Editable`s within the `EditableDialogBoxConfiguration`.

Steps to reproduce:
1. Add `pimcore_areablock`
2. Add configurable area.
3. Save (configuration is now stored in the database).
4. Remove the area using Pimcore UI.
5. Save again (configuration is still available).

Using `v6.8.5`.

---
![image](https://user-images.githubusercontent.com/57256630/107354680-be184180-6ace-11eb-8a8b-a3b2adbc87f6.png)

![image](https://user-images.githubusercontent.com/57256630/107354717-c96b6d00-6ace-11eb-8956-181636a20933.png)

**Comment by zoidbergx** [comment]
If someone still having this issue, we're heading into the same and created a workaround.
Maybe someone help this out.

As my understanding the problem has two parts:

- The whole document is saved in the session
- Existing deleteable are not correctly cleared by Pimcore

During the update routine pimcore deletes all editables in the "documents_elements" table but the delete is in the lifetime where the object is already loaded with its editable property. The next line after the delete is to create all editables from the object property itself so in this case Pimcore never cleans up the table and also unused elements kept in the DB.

We made an overwrite of the saveAction from the ` CandoCX\CoreBundle\Controller\Admin\Document\PageController`:

```php
    public function saveAction(Request $request)
    {
        $page = Document\Page::getById($request->get('id'), true);
        if ($page) {
            $this->removeFromSessionAction($request);
            $page->getDao()->deleteAllEditables();
        }
        return parent::saveAction($request);
    }
```

**Comment by dvesh3** [comment]
> This also holds true for `Editable`s within the `EditableDialogBoxConfiguration`.
> 
> Steps to reproduce:
> 
> 1. Add `pimcore_areablock`
> 2. Add configurable area.
> 3. Save (configuration is now stored in the database).
> 4. Remove the area using Pimcore UI.
> 5. Save again (configuration is still available).
> 
> Using `v6.8.5`.
> 
> ![image](https://user-images.githubusercontent.com/57256630/107354680-be184180-6ace-11eb-8a8b-a3b2adbc87f6.png)
> 
> ![image](https://user-images.githubusercontent.com/57256630/107354717-c96b6d00-6ace-11eb-8956-181636a20933.png)

@passioneight Not valid anymore. This should cleanup all editables on save https://github.com/pimcore/pimcore/blob/10.x/models/Document/PageSnippet.php#L133

**Comment by dvesh3** [comment]
Fixed by #11612

**Comment by janisverins** [comment]
@dvesh3 @brusch This is a bug still on v6.9.7. Any tip? Stuck on debugging this.
Thanks in advance.

**Comment by dvesh3** [comment]
@janisverins Hi, the fix was merged into 10.3.3 version and Pimcore 6 is not supported anymore. You can easily apply the patch in your project from [here](https://github.com/pimcore/pimcore/pull/11612/files#diff-c64e05243f21155611cdc45c031195f4365ca67e03c2b34ea581f6aa6ea4eb79R446-R447) as this is just 2 lines of change.

**Comment by janis-verins** [comment]
@dvesh3 Yes, unfortunately the project is quite old and wont switch to version 10+ in the nearest future.
Thanks you, I saw the fix, but the method (areabrickRenderIndexEditmode()) does not exist in the pimcore version we use.
Any quick solution for the version v6.9.7?

**Comment by dvesh3** [comment]
@janis-verins  yes, this method was result of refactoring on Pimcore 10 to make areablocks work without reload. Sorry, I'm not sure about the exact fix on 6.9. Just a tip, you can look at the refactoring changes here https://github.com/pimcore/pimcore/commit/47d05ddd2ef472528f25c78ea7390c0e7d470199 to see where to apply the fix.

**Comment by janis-verins** [comment]
@dvesh3 Maybe you remember or have an idea where pimcore cleared editables from documents_elements in the version 6.9.x?

**Comment by janis-verins** [comment]
@dvesh3 At the moment the only solution I see is to add
`  $this->removeFromSessionAction($request); `
In saveAction() and in saveToSessionAction() methods to clear data from tmp_store table.
Advise please if this does not make sense.

**Comment by dvesh3** [comment]
Use `Document\Service::removeElementFromSession('document', $request->request->getInt('id')` to clear the data from tmpstore.

**Comment by janis-verins** [comment]
Yes, thank you!!

**Comment by janis-verins** [comment]
@dvesh3 FYI the fix for me looks like this in the PageController.php class

```
  public function saveAction(Request $request)
  {
        $page = Document\Page::getById($request->get('id'));

        if (!$page) {
            throw $this->createNotFoundException('Page not found');
        }

        $this->removeFromSessionAction($request);
        
        /** @var Document\Page|null $pageSession */
        $pageSession = $this->getFromSession($page);
        
        ...
```

```
public function saveToSessionAction(Request $request)
{
        $this->removeFromSessionAction($request);

        return parent::saveToSessionAction($request);
    }
```
The only thing is that, in the saveAction() method it now looks kind of weird that document is removed from the session and then again asked for from the session. (Maybe that part can be removed when doing the fix this way)
So probably not the best fix in v6.9.x
