### ISSUE TITLE
[Bug]: Classes-rebuild fails for class dependent optionprovider

### ISSUE THREAD

**Issue by roland4432** [pimcore/pimcore#9991]
### Expected behavior

The console command pimcore:deployment:classes-rebuild should work under any circumstances.

### Actual behavior

The command fails if the order of the classes in the database is defined in an order that will break the rebuild command.

When running the classes-rebuild command, the build mechanism for the files under var/classes/DataObject will trigger the method _presave_, which will then call the _getOptions_ from the optionprovider and fail under certain cirumstances.

### Steps to reproduce

* Create a class 'A' with a select and set an optionprovider for its values (and create the optionprovider)
* Create a class 'B'
* The method _getOptions_ in the optionprovider will instance the listing from class 'B'
* Delete var/classes/DataObject folder for a clean rebuild (to simulate a deployment e.g. on Azure, where the artifact is always created without existing DataObjects or Listings)
* Call console command pimcore:deployment:classes-rebuild -c
* If the database table _classes_ is set to order A before B, then classes-rebuild will fail with the message: 'Cannot load class Listing in OptionProvider.php (the one created under the first step)

**Comment by akno77** [comment]
I have a similar problem under Pimcore 10.1.1 (10.0.9 works correct):

1. I have a Data Object Class `Article `with an options provider Class (`DropdownMultiSelectOptionsProvider`) which uses another Data Object Class `Dropdown`
2. If I run the command `pimcore:deployment:classes-rebuild -c -vv` it fails for the `Article` Class with: 

```
In DropdownMultiSelectOptionsProvider.php line 30:
                                                                               
  [Symfony\Component\ErrorHandler\Error\ClassNotFoundError]                    
  Attempted to load class "Dropdown" from namespace "Pimcore\Model\DataObject".                                                                           
  Did you forget a "use" statement for another namespace?   
```
It is a fatal error and no other classes are rebuild after this error!

When I downgrade to Pimcore 10.0.9 it works again.

**Comment by brusch** [comment]
@roland4432 @akno77 can maybe someone provide a PR for that? Thanks a lot in advance!

**Comment by roland4432** [comment]
@brusch Can do sir. Would you be fine with just reordering the build mechanism to create all Listings first and then the DataObjects? Might already do the trick

**Comment by brusch** [comment]
@roland4432 yep, let's try that first! Thanks!

**Comment by roland4432** [comment]
Hello @brusch,

there is a very simple solution, that I could offer, but wanna talk about that first.
When saving classes from definition files, the method _preSave_ will be called when a multiselect field is filled via optionProvider.

IMHO this is not necessary, when creating the the classes via console command.
So.. the easiest and fastest solution (but maybe not your preferred one) could look like this:

```php
#models/DataObject/ClassDefinition; line 404
...
    public function save($saveDefinitionFile = true)
    {
        $fieldDefinitions = $this->getFieldDefinitions();
        foreach ($fieldDefinitions as $fd) {
            if ($fd->isForbiddenName()) {
                throw new \Exception(sprintf('Forbidden name used for field definition: %s', $fd->getName()));
            }

            if ($fd instanceof DataObject\ClassDefinition\Data\DataContainerAwareInterface && php_sapi_name() != "cli") { // <- check if script is called from command line and skip preSave if so
                $fd->preSave($this);
            }
        }
...
```


I am not even sure, why the _preSave_ method calls the optionProvider which then calls the _getOptions_ at all. Is this due to caching warmups? Maybe you can enlighten me :)
Thank you

@akno77: Can you confirm a working _classes-rebuild_ with the given fix?

**Comment by brusch** [comment]
I'm afraid that this has the potential to break other things, because it could be also a different command running on CLI doing a class definition save. 
I think we need to tackle this in the data-type class somehow.

**Comment by roland4432** [comment]
Alrighty then. I would stick to the original plan and change the order of the building process.
I'll keep you updated :)

**Comment by roland4432** [comment]
See  #10192 for a better way to handle this, than just reordering stuff and make more loop actions

**Comment by akno77** [comment]
Is a fix planned for 10.1.3? Because currently our automated deployment doesn't work anymore with this bug!

**Comment by roland4432** [comment]
@akno77: My PR is merged (should therefore be released with 10.1.3) and this ticket can be closed @dvesh3 or @brusch. Thx

Check #10192 for reference.

**Comment by brusch** [comment]
Fixed by #10192

**Comment by akno77** [comment]
I still get this error with Pimcore 10.1.3 using the console command `pimcore:deployment:classes-rebuild`:

```
In DropdownMultiSelectOptionsProvider.php line 30:
                                                                               
  [Symfony\Component\ErrorHandler\Error\ClassNotFoundError]                    
  Attempted to load class "Dropdown" from namespace "Pimcore\Model\DataObject  
  ".                                                                           
  Did you forget a "use" statement for another namespace?                      
                                                                               

Exception trace:
  at /var/www/html/src/Website/OptionsProvider/DropdownMultiSelectOptionsProvider.php:30
 App\Website\OptionsProvider\DropdownMultiSelectOptionsProvider->getOptions() at /var/www/html/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/Multiselect.php:713
 Pimcore\Model\DataObject\ClassDefinition\Data\Multiselect->preSave() at /var/www/html/vendor/pimcore/pimcore/models/DataObject/ClassDefinition.php:414
 Pimcore\Model\DataObject\ClassDefinition->save() at /var/www/html/vendor/pimcore/pimcore/bundles/CoreBundle/Command/ClassesRebuildCommand.php:117
 Pimcore\Bundle\CoreBundle\Command\ClassesRebuildCommand->execute() at /var/www/html/vendor/symfony/console/Command/Command.php:299
 Symfony\Component\Console\Command\Command->run() at /var/www/html/vendor/symfony/console/Application.php:996
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/framework-bundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/console/Application.php:295
 Symfony\Component\Console\Application->doRun() at /var/www/html/vendor/symfony/framework-bundle/Console/Application.php:82
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/html/vendor/symfony/console/Application.php:167
 Symfony\Component\Console\Application->run() at /var/www/html/bin/console:36
```

**Comment by roland4432** [comment]
@akno77  I wonder how line 713 in the MultiSelect.php file could bubble that error up to your Optionsprovider since it should handle the error right in the catch part.

Mind sharing your DropdownMultiSelectOptionsProvider? Or at least the lines from around line 30?

**Comment by akno77** [comment]
@roland4432 Here is the code part until line 36:

```
<?php

namespace App\Website\OptionsProvider;

use Exception;
use Pimcore\Model\DataObject\ClassDefinition\Data;
use Pimcore\Model\DataObject\ClassDefinition\DynamicOptionsProvider\MultiSelectOptionsProviderInterface ;
use Pimcore\Model\DataObject\Dropdown;

/**
 * OptionsProvider based on "Dropdown" data object.
 * 
 * "Options Provider Data" example usage: {"dropdown": "/Dropdowns/mydropdown"}
 */
class DropdownMultiSelectOptionsProvider implements MultiSelectOptionsProviderInterface 
{
    /**
     * @param array $context
     * @param Data $fieldDefinition
     * @return array
     * @throws Exception
     */
    public function getOptions($context, $fieldDefinition)
    {
        $dropdownPath = $this->getOptionsProviderData($fieldDefinition)->dropdown;
        if (empty($dropdownPath)) {
            throw new Exception('No dropdown path is provided!');
        }

        $dropdown = Dropdown::getByPath($dropdownPath);
        if (empty($dropdown) || !$dropdown instanceof Dropdown) {
            throw new Exception('Dropdown path does not exist: '. $dropdownPath);
        }

        return $dropdown->getItems();
    }
```

**Comment by roland4432** [comment]
You are right. I used a not sufficient enough way to catch errors with my PR. Let me fix this and make a PR real quick.

In the meantime this will help you:

```php
public function getOptions($context, $fieldDefinition)
    {
	try{
		$dropdownPath = $this->getOptionsProviderData($fieldDefinition)->dropdown;
		if (empty($dropdownPath)) {
		    throw new Exception('No dropdown path is provided!');
		}

		$dropdown = Dropdown::getByPath($dropdownPath);
		if (empty($dropdown) || !$dropdown instanceof Dropdown) {
		    throw new Exception('Dropdown path does not exist: '. $dropdownPath);
		}

		return $dropdown->getItems();
	} catch (\Throwable $e){
		throw new Exception('Class not loaded');	
	}
    }
```
